export const GET_CITY = "GET_CITY";
export const GET_CITY_SUCCESS = "GET_CITY_SUCCESS";
export const GET_CITY_ERROR = "GET_CITY_ERROR";

export const CITY_COMPARISON = "CITY_COMPARISON";
export const CITY_COMPARISON_SUCCESS = "CITY_COMPARISON_SUCCESS";
export const CITY_COMPARISON_ERROR = "CITY_COMPARISON_ERROR";

export const REMOVE_CITY = "REMOVE_CITY";
export const CLEAR_ALL_CITIES = "CLEAR_ALL_CITIES";
